/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mySystem;

/**
 *
 * @author iamAxylle
 */
public class ExpenseChart extends javax.swing.JDialog {

    /**
     * Creates new form SalesandExpenseChart
     */
    public ExpenseChart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Externs.centerForm(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10 = pieChart();
        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 900, 440));

        jLabel156.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expesepie.png"))); // NOI18N
        jPanel1.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel157.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel157.setText("Expense Chart");
        jLabel157.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel15.setText("- View expense chart");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel pieChart() {
        org.jfree.data.general.DefaultPieDataset pieDataset = new org.jfree.data.general.DefaultPieDataset();
        String[] expensetype = {"Raw Supplies",  "Drawing", "Utility Expense",  "Wholesales",   "Kitchenwares", "Salary Expense"};
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            for (int i = 0; i < 6; i++) {
                double expense = 0;
                String SQL = "select * from EXPENSE where expensetype = '" + expensetype[i] + "'";
                java.sql.PreparedStatement pst = con.prepareStatement(SQL);
                java.sql.ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    expense += rs.getDouble("price");
                }
                pieDataset.setValue(expensetype[i], expense);
            }
            con.close();
        } catch (java.sql.SQLException err) {
            System.out.println(err);
        }
        org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createPieChart3D("Expense Chart", pieDataset, true, true, true);
        org.jfree.chart.plot.PiePlot P = (org.jfree.chart.plot.PiePlot) chart.getPlot();
        return new org.jfree.chart.ChartPanel(chart);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExpenseChart dialog = new ExpenseChart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    // End of variables declaration//GEN-END:variables
}
