/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mySystem;

import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;

/**
 *
 * @author iamAxylle
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Encryptor v1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 30));

        jTextField2.setFont(new java.awt.Font("Lucida Console", 0, 10)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 30));

        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

        jButton2.setText("Compare");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, 30));

        jDateChooser1.setDateFormatString("MMMM d, yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 250, 30));

        jButton5.setText("Pie Chart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jButton7.setText("Bar Chart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jButton8.setText("Line Chart");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        chartPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(chartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 870, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Password a = new Password();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(Externs.fixImagePath(jTextField1.getText()));
        try {
            String hashed = Password.encrypt(jTextField1.getText());
            jTextField2.setText(hashed);
        }
        catch(Exception e) {
            System.out.println(e);
        }
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "select * from EMPLOYEE where id = 11";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            int count = 0;
            while (rs.next()) {
                jDateChooser1.setDate(rs.getDate("Birthdate"));
                count++;
            }
            con.close();
        } catch (java.sql.SQLException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String result;
        try {
            if (Password.check(jTextField1.getText(), jTextField2.getText()) == true) {
                result = "Password OK";
            }
            else {
                result = "Password not equal";
            }
            javax.swing.JOptionPane.showMessageDialog(null, result);
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        org.jfree.data.general.DefaultPieDataset pieDataset = new org.jfree.data.general.DefaultPieDataset();
        pieDataset.setValue("One", new Integer(10));
        pieDataset.setValue("Two", new Integer(20));
        pieDataset.setValue("Three", new Integer(30));
        pieDataset.setValue("Four", new Integer(40));
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", pieDataset, true, true, true);
        PiePlot P = (PiePlot) chart.getPlot();
        //P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
    }//GEN-LAST:event_jButton5ActionPerformed

    public JPanel BarChart2Panel() {
    org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        dataset.setValue(3800, "Marks", "January");
        dataset.setValue(1200, "Mark", "January");
        dataset.setValue(4750, "Marks", "February");
        dataset.setValue(2950, "Mark", "February");
        dataset.setValue(875, "Marks", "March");
        dataset.setValue(1950, "Mark", "March");
        
        JFreeChart chart = ChartFactory.createBarChart3D("Bar Chart Title", "Stdent Names x-axis", "Marks y-axis", dataset, org.jfree.chart.plot.PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.black);
        return new ChartPanel(chart);
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        /**
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        dataset.setValue(3800, "Marks", "January");
        dataset.setValue(1200, "Mark", "January");
        dataset.setValue(4750, "Marks", "February");
        dataset.setValue(2950, "Mark", "February");
        dataset.setValue(875, "Marks", "March");
        dataset.setValue(1950, "Mark", "March");
        
        JFreeChart chart = ChartFactory.createBarChart3D("Bar Chart Title", "Stdent Names x-axis", "Marks y-axis", dataset, org.jfree.chart.plot.PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.black);
        
        ChartFrame frame = new ChartFrame("Bar Chart - Frame Title", chart);
        chartPanel.add(frame);
        //frame.setVisible(true);
        //frame.setSize(450, 500);
        */ 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        dataset.setValue(80, "1", "January");
        dataset.setValue(70, "2", "January");
        dataset.setValue(65, "1", "February");
        dataset.setValue(95, "2", "February");
        dataset.setValue(90, "1", "March");
        dataset.setValue(50, "2", "March");
        dataset.setValue(85, "1", "April");
        dataset.setValue(75, "2", "April");
        dataset.setValue(100, "1", "May");
        dataset.setValue(95, "2", "May");
        dataset.setValue(60, "1", "June");
        dataset.setValue(100, "2", "June");
        
        JFreeChart chart = ChartFactory.createLineChart("Line Chart Title", "Stdent Names x-axis", "Marks y-axis", dataset, org.jfree.chart.plot.PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.black);
        //P.addAnnotation(ShapeAnnotation, true);
        //P.setSeriesShapesVisible(1, true);
        ChartFrame frame = new ChartFrame("Line Chart - Frame Title", chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Widows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
