/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mySystem;

import java.awt.Color;

/**
 *
 * @author iamAxylle
 */
public class Qwerty extends javax.swing.JFrame {

    /**
     * Creates new form Qwerty
     */
    public Qwerty() {
        initComponents();
        Externs.centerForm(this);
        setDate();
        itemNameList();
        jLabel114.setText(Externs.whoLoggedIn());
        jLabel123.setText(String.valueOf(Externs.checkSales()));
        Externs.fillTable(jTable4);
        Externs.fillTable2(jTable2);
        Externs.fillTable4(jTable7);
        if (Externs.setTab() == 1) {
            jTabbedPane1.setEnabledAt(3, false);
            jTabbedPane1.setEnabledAt(4, false);
            jTabbedPane1.setEnabledAt(6, false);
            jTabbedPane1.setEnabledAt(7, false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel164 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel167 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Qwerty Enterprise System v1.0");
        setMaximumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(51, 51, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("|");
        jLabel102.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel12.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 20, 30));

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("Aministrator");
        jPanel12.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, 30));

        jLabel115.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Total Sales:");
        jPanel12.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 30));

        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("September");
        jPanel12.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 60, 15));

        jLabel117.setForeground(new java.awt.Color(255, 255, 255));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("9999");
        jPanel12.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 15, 60, 15));

        jLabel118.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 255));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("39");
        jPanel12.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, 30));

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("|");
        jLabel103.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel12.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 20, 30));

        jLabel162.setBackground(new java.awt.Color(51, 51, 255));
        jLabel162.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel162.setText("Logout");
        jLabel162.setToolTipText("");
        jLabel162.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel162.setOpaque(true);
        jLabel162.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel162MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 50, 30));

        jLabel119.setBackground(new java.awt.Color(51, 51, 255));
        jLabel119.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(255, 255, 255));
        jLabel119.setText("Change Password");
        jLabel119.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel119.setOpaque(true);
        jLabel119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel119MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 120, 30));

        jLabel120.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setText("Login as");
        jPanel12.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 55, 30));

        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 110, 30));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1100, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Click a module to get started!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1090, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Team Chuwariwriwap Extension"));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Shin");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 20));

        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Alex");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jLabel5.setOpaque(true);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 270));

        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Nick");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 20));

        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Axylle");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 20));

        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Gab");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 580, 320));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/home.gif")), jPanel1, ""); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel158.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sales.gif"))); // NOI18N
        jPanel7.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel159.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel159.setText("Sales Register");
        jLabel159.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel16.setText("- Process sales and returns");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jScrollPane5.setToolTipText("");

        jTable5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Quantity", "Stock", "Price", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setRowHeight(25);
        jTable5.setRowMargin(2);
        jTable5.getTableHeader().setReorderingAllowed(false);
        jTable5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable5FocusGained(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(1).setMinWidth(70);
            jTable5.getColumnModel().getColumn(1).setMaxWidth(70);
            jTable5.getColumnModel().getColumn(2).setMinWidth(70);
            jTable5.getColumnModel().getColumn(2).setMaxWidth(70);
            jTable5.getColumnModel().getColumn(3).setMinWidth(100);
            jTable5.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable5.getColumnModel().getColumn(4).setMinWidth(100);
            jTable5.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 790, 350));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 320, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Item Description:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Walk-in" }));
        jPanel7.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 200, 30));

        jLabel10.setText("Select Costumer (Optional)");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, -1, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "Sale Controls"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.jpg"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.jpg"))); // NOI18N
        jButton3.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, 30));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, 60));

        jLabel11.setText("Total");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, 20));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 200, 30));

        jLabel12.setText("Cash Recieved");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, 20));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 200, 30));

        jLabel14.setText("Change");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, -1, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 200, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Compute");
        jButton1.setEnabled(false);
        jButton1.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 80, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("New");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 80, 30));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText("Debt");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("QTY:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 30));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner1.setValue(1);
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 50, 30));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/sales.gif")), jPanel7); // NOI18N

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(1100, 670));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/item.gif"))); // NOI18N
        jPanel3.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel122.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel122.setText("Inventory");
        jLabel122.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Supplier", "Raw Price", "Retail Price", "Stock"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable2FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(70);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(2).setMinWidth(150);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable2.getColumnModel().getColumn(3).setMinWidth(90);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(90);
            jTable2.getColumnModel().getColumn(4).setMinWidth(90);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(90);
            jTable2.getColumnModel().getColumn(5).setMinWidth(70);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 870, 480));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("New Item");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));

        jLabel13.setText("- Add, Update, Delete, and Search items");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.jpg"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 30, 30));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 300, 30));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton9.setText("Add Stock");
        jButton9.setEnabled(false);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, 30));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/item.gif")), jPanel3); // NOI18N

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("- Add Expenses");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel163.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel163.setText("Expenses");
        jLabel163.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jScrollPane6.setToolTipText("");

        jTable6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Expense", "ExpenseType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.setRowHeight(25);
        jTable6.setRowMargin(2);
        jTable6.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setMinWidth(120);
            jTable6.getColumnModel().getColumn(0).setMaxWidth(120);
            jTable6.getColumnModel().getColumn(2).setMinWidth(130);
            jTable6.getColumnModel().getColumn(2).setMaxWidth(130);
            jTable6.getColumnModel().getColumn(3).setMinWidth(200);
            jTable6.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPanel9.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 870, 480));

        jLabel164.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expense.png"))); // NOI18N
        jPanel9.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton18.setText("Add");
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setOpaque(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));
        jPanel9.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 300, 30));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.jpg"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 30, 30));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/expense.png")), jPanel9); // NOI18N

        jPanel8.setName(""); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(1100, 670));
        jPanel8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel8FocusGained(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel160.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employees.gif"))); // NOI18N
        jPanel8.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel161.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel161.setText("Human Resource");
        jLabel161.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel17.setText("- Add, Update, Delete, and Search employees, suppliers or costumers");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton13.setText("New");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setOpaque(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));

        jButton14.setBackground(new java.awt.Color(204, 204, 204));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton14.setText("Update");
        jButton14.setEnabled(false);
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.setOpaque(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, 30));

        jButton15.setBackground(new java.awt.Color(255, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setText("Delete");
        jButton15.setEnabled(false);
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.setOpaque(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 30));

        jScrollPane4.setToolTipText("");

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Employee ", "E-mail", "Contact Num", "Address"
            }
        ));
        jTable4.setRowHeight(25);
        jTable4.setRowMargin(2);
        jTable4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable4.getTableHeader().setReorderingAllowed(false);
        jTable4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable4FocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(1).setMinWidth(130);
            jTable4.getColumnModel().getColumn(1).setMaxWidth(130);
            jTable4.getColumnModel().getColumn(2).setMinWidth(120);
            jTable4.getColumnModel().getColumn(2).setMaxWidth(120);
            jTable4.getColumnModel().getColumn(3).setMinWidth(200);
            jTable4.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 870, 480));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.jpg"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 30, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 300, 30));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/employees.gif")), jPanel8); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel165.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/attendance.png"))); // NOI18N
        jPanel10.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel166.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel166.setText("Attendance");
        jLabel166.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel10.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel38.setText("- employee login, logout, attendance");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jScrollPane7.setToolTipText("");

        jTable7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "ID", "Login", "Logout", "Salary"
            }
        ));
        jTable7.setRowHeight(25);
        jTable7.setRowMargin(2);
        jTable7.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setMinWidth(120);
            jTable7.getColumnModel().getColumn(0).setMaxWidth(120);
            jTable7.getColumnModel().getColumn(2).setMinWidth(200);
            jTable7.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel10.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 870, 480));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 300, 30));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.jpg"))); // NOI18N
        jPanel10.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 30, 30));

        jButton23.setBackground(new java.awt.Color(204, 204, 204));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton23.setText("In / Out");
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.setOpaque(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/attendance.png")), jPanel10); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel156.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reports.gif"))); // NOI18N
        jPanel5.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel157.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel157.setText("Reports");
        jLabel157.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel15.setText("- View sales reports");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sales.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, 75));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/debtreport2.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 60, 75));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Expense");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Sales");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expense3.png"))); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 60, 75));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Receivable");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salesreport2.jpg"))); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 60, 75));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Sales and Expense Chart");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jLabel31.setText("-view receivables");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel32.setText("-view sales and expense chart");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        jLabel33.setText("-view personnel sales");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel34.setText("-view expenses");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expesepie.png"))); // NOI18N
        jLabel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 60, 75));

        jLabel36.setText("-view expense chart");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Expense Chart");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/reports.gif")), jPanel5); // NOI18N

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel167.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel167.setText("Store Configuration");
        jLabel167.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 30));

        jLabel39.setText("- Manage store configuration");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/storeconfig.gif"))); // NOI18N
        jPanel11.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rates.png"))); // NOI18N
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, 75));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Rates");
        jPanel11.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel42.setText("-set employee salary rates");
        jPanel11.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/image/storeconfig.gif")), jPanel11); // NOI18N

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNameList() {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Walk-in");
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "SELECT * FROM ITEMS WHERE QUANTITY != 0 ORDER BY ITEMNAME ASC";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("ITEMNAME"));
            }
            SQL = "SELECT * FROM PERSONS WHERE ISDELETED = 0 AND TYPE = 2 ORDER BY LASTNAME ASC";
            pst = con.prepareStatement(SQL);
            rs = pst.executeQuery();
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("FIRSTNAME") + " " + rs.getString("LASTNAME"));
            }
            con.close();
        } catch (java.sql.SQLException err) {
            System.out.println(err);
        }
    }

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        String employeeid = "" + jTable4.getValueAt(jTable4.getSelectedRow(), 0);
        if (("".equals(employeeid)) || ("null".equals(employeeid))) {
        } else {
            Externs.deletePerson(employeeid);
            Externs.fillTable(jTable4);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    //New employee
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        NewPerson dialog = new NewPerson(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        itemNameList();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jLabel162MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel162MouseClicked
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel162MouseClicked

    //Search
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        Externs.clearTable(jTable4);
        int count = 0;
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "select * from PERSONS where "
                    + "lower(firstname) like '" + jTextField7.getText().toLowerCase() + "%' or "
                    + "lower(lastname) like '" + jTextField7.getText().toLowerCase() + "%' or "
                    + "idnumber like '" + jTextField7.getText() + "%' "
                    + "order by lastname asc";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                if ((rs.getInt("isdeleted") == 0) && (!"axylle".equals(rs.getString("userkey")))) {
                    jTable4.setValueAt(rs.getObject("idnumber"), count, 0);
                    jTable4.setValueAt(rs.getObject("firstname") + " " + rs.getObject("LASTNAME"), count, 1);
                    jTable4.setValueAt(rs.getObject("email"), count, 2);
                    jTable4.setValueAt(rs.getObject("phone"), count, 3);
                    jTable4.setValueAt(rs.getObject("address"), count, 4);
                    count++;
                }
            }
            if (count == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "No record found.");
            }
            con.close();
        } catch (java.sql.SQLException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    //enable/disable delete button
    private void jTable4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable4FocusGained
        // TODO add your handling code here:
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
    }//GEN-LAST:event_jTable4FocusGained

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String employeeid = "" + jTable4.getValueAt(jTable4.getSelectedRow(), 0);
        if (("".equals(employeeid)) || ("null".equals(employeeid))) {
        } else {
            Externs.updatePerson(employeeid);
            EditPerson dialog = new EditPerson(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
            Externs.fillTable(jTable4);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jPanel8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel8FocusGained
        // TODO add your handling code here:
        Externs.fillTable(jTable4);
    }//GEN-LAST:event_jPanel8FocusGained

    private void jTable5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable5FocusGained
        // TODO add your handling code here:
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jTable5FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solditems = "";
        jButton1.setEnabled(false);
        int errorflag = 0;

        if (jCheckBox1.isSelected() == false) {
            if ("".equals(jTextField2.getText())) {
                jTextField2.setBackground(Color.red);
                errorflag = 1;
            } else {
                jTextField3.setText(String.valueOf(total - Double.parseDouble(jTextField2.getText())));
            }
        }
        if (errorflag == 0) {
            try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
                String SQL = "SELECT * FROM sales";
                java.sql.PreparedStatement pst = con.prepareStatement(SQL);
                java.sql.ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    solditems += rs.getString("quantity") + "-" + rs.getString("itemname") + ", ";
                    SQL = "UPDATE items SET "
                            + "quantity = quantity - " + rs.getString("quantity") + " where "
                            + "itemname = '" + rs.getString("itemname") + "'";
                    pst = con.prepareStatement(SQL);
                    pst.executeUpdate();
                }
                SQL = "INSERT INTO transactions (transactiondate, solditems, total, costumername, cashier) values ("
                        + "'" + date + "', "
                        + "'" + solditems + "', "
                        + total + ", "
                        + "'" + jComboBox2.getSelectedItem() + "', "
                        + "'" + Externs.whoLoggedIn() + "')";
                pst = con.prepareStatement(SQL);
                pst.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(null, "Item Recorded.");
                con.close();
            } catch (java.sql.SQLException | NumberFormatException err) {
                javax.swing.JOptionPane.showMessageDialog(null, err);
            }
            if (Externs.checkSales() >= 10000) {
                jLabel115.setText("Sales Quota Reached.");
            }
            jLabel123.setText(String.valueOf(Externs.checkSales()));
            Externs.deleteSales();
            Externs.clearTable(jTable5);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
        }
        jCheckBox1.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "DELETE FROM SALES WHERE ITEMNAME = '" + jTable5.getValueAt(jTable5.getSelectedRow(), 0) + "'";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            pst.executeUpdate();
        SQL = "SELECT * FROM sales";
            pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            total = 0;
            while (rs.next()) {
                total += rs.getDouble("subtotal");
            }
            con.close();

        } catch (java.sql.SQLException err) {
            javax.swing.JOptionPane.showMessageDialog(null, err);
        }
        Externs.clearTable(jTable5);
        Externs.showSales(jTable5);
        jTextField1.setText(new java.text.DecimalFormat("#,###.00").format(total));
    }//GEN-LAST:event_jButton2ActionPerformed
    double total = 0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        double quantityItems = 0, quantitySales = 0, sellprice = 0, subtotal = 0;
        int count = 0;
        jButton4.setEnabled(true);
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "select * from sales where itemname = '" + jComboBox1.getSelectedItem() + "'";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                count++;
                quantitySales = rs.getDouble("quantity"); //getsalesquantity
            }
            SQL = "select * from items where itemname = '" + jComboBox1.getSelectedItem() + "'";
            pst = con.prepareStatement(SQL);
            rs = pst.executeQuery();
            while (rs.next()) {
                quantityItems = rs.getDouble("quantity"); //getStock
                sellprice = rs.getDouble("sellprice"); //selling price
            }


            if (quantityItems < (quantitySales + Double.parseDouble(jSpinner1.getValue().toString()))) {
                javax.swing.JOptionPane.showMessageDialog(null, "Stock Error\nRemaining stock: " + (quantityItems - quantitySales));
            } else {
                if (count == 0) {
                    quantitySales = Double.parseDouble(jSpinner1.getValue().toString());
                    subtotal = quantitySales * sellprice;
                    SQL = "INSERT INTO sales (itemname, quantity, sellprice, subtotal, stock) VALUES ("
                            + "'" + (String) jComboBox1.getSelectedItem() + "',"
                            + "" + quantitySales + ","
                            + "" + sellprice + ","
                            + "" + subtotal + ","
                            + "" + quantityItems + ")";
                } else {
                    quantitySales += Double.parseDouble(jSpinner1.getValue().toString());
                    subtotal = quantitySales * sellprice;
                    SQL = "UPDATE sales SET "
                            + "quantity = " + quantitySales + ", "
                            + "subtotal = " + subtotal
                            + " WHERE itemname = '" + (String) jComboBox1.getSelectedItem() + "'";
                }
                pst = con.prepareStatement(SQL);
                pst.executeUpdate();
            }
            SQL = "SELECT * FROM sales";
            pst = con.prepareStatement(SQL);
            rs = pst.executeQuery();
            total = 0;
            while (rs.next()) {
                count++;
                total += rs.getDouble("subtotal");
            }
            con.close();

        } catch (java.sql.SQLException err) {
            javax.swing.JOptionPane.showMessageDialog(null, err);
        }
        jTextField1.setText(new java.text.DecimalFormat("#,###.00").format(total));
        jSpinner1.setValue(1);
        Externs.clearTable(jTable5);
        Externs.showSales(jTable5);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        NewItem dialog = new NewItem(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        Externs.fillTable2(jTable2);
        itemNameList();
    }//GEN-LAST:event_jButton6ActionPerformed

    //Search item
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Externs.clearTable(jTable2);
        int count = 0;
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "select * from ITEMS where "
                    + "lower(itemname) like '" + jTextField5.getText().toLowerCase() + "%' or "
                    + "lower(supplier) like '" + jTextField5.getText().toLowerCase() + "%' "
                    + "order by itemname asc";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            System.out.println(SQL);
            while (rs.next()) {
                jTable2.setValueAt(rs.getObject("id"), count, 0);
                jTable2.setValueAt(rs.getObject("itemname"), count, 1);
                jTable2.setValueAt(rs.getObject("supplier"), count, 2);
                jTable2.setValueAt(rs.getString("rawprice"), count, 3);
                jTable2.setValueAt(rs.getString("sellprice"), count, 4);
                jTable2.setValueAt(rs.getString("quantity"), count, 5);
                count++;
            }
            if (count == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Zero querry result");
            }
            con.close();
        } catch (java.sql.SQLException err) {
            javax.swing.JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Externs.itemEditFlag("");
        if ((jTable2.getValueAt(jTable2.getSelectedRow(), 1)) == null) {
        } else {
            Externs.itemEditFlag(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 1)));
            AddStock dialog = new AddStock(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
            Externs.fillTable2(jTable2);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusGained
        // TODO add your handling code here:
        jButton9.setEnabled(true);
    }//GEN-LAST:event_jTable2FocusGained

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jj.jpg")));
        jLabel4.setText("John-John Fortaleza Fainsan");
        jLabel6.setText("Head Programer, System Dessign");
        jLabel7.setText("john.fortaleza@yahoo.com");
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gab.jpg")));
        jLabel4.setText("Robert Gabriel Fortuno Espiritu");
        jLabel6.setText("Assistant Programmer, Researcher");
        jLabel7.setText("gariel_42no@yahoo.com");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/alex.jpg")));
        jLabel4.setText("Alexandria Perdiguerra Fidellaga");
        jLabel6.setText("Documentation, Researcher, Icon Design");
        jLabel7.setText("alxfidellaga@yahoo.com");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ann.jpg")));
        jLabel4.setText("Anne Loraine Lorenzana Anapi");
        jLabel6.setText("Programmer, System Design");
        jLabel7.setText("anneloraineanapi@yahoo.com");
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shin.jpg")));
        jLabel4.setText("Clarshin Hazel Pua Accad");
        jLabel6.setText("Documentation, Researcher");
        jLabel7.setText("clarshin_accad@yahoo.com");
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        if (total == 0) {
        } else {
            jButton1.setEnabled(true);
            jTextField2.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setEnabled(false);
        Externs.clearTable(jTable5);
        Externs.deleteSales();
        Externs.showSales(jTable5);
        jButton1.setEnabled(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected() == true) {
            jButton5.setEnabled(true);
            jComboBox2.removeItemAt(0);
            jLabel10.setText("Select Costumer (Required)");
            if (total == 0) {
            } else {
                jButton1.setText("Record");
                jButton1.setEnabled(true);
            }
        } else {
            jButton5.setEnabled(false);
            itemNameList();
            jLabel10.setText("Select Costumer (Optional)");
            jButton1.setText("Compute");
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        SalesReport dialog = new SalesReport(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        DebtReport dialog = new DebtReport(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DebtForm dialog = new DebtForm(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel119MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel119MouseClicked
        // TODO add your handling code here:
        ChangePassword dialog = new ChangePassword(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel119MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        AddExpense dialog = new AddExpense(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        Externs.clearTable(jTable6);
        int count = 0;
        try (java.sql.Connection con = java.sql.DriverManager.getConnection(Externs.host, Externs.username, Externs.password)) {
            String SQL = "select * from EXPENSE where "
                    + "lower(DESCRIPTION) like '" + jTextField6.getText().toLowerCase() + "%'"
                    + "order by DESCRIPTION asc";
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            java.sql.ResultSet rs = pst.executeQuery();
            System.out.println(SQL);
            while (rs.next()) {
                jTable6.setValueAt(rs.getObject("REGDATE"), count, 0);
                jTable6.setValueAt(rs.getObject("DESCRIPTION"), count, 1);
                jTable6.setValueAt(rs.getObject("PRICE"), count, 2);
                jTable6.setValueAt(rs.getString("EXPENSETYPE"), count, 3);
                count++;
            }
            if (count == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Zero querry result");
            }
            con.close();
        } catch (java.sql.SQLException err) {
            javax.swing.JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        SalesandExpenseChart dialog = new SalesandExpenseChart(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        ExpenseReport dialog = new ExpenseReport(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        ExpenseChart dialog = new ExpenseChart(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        EmployeeRates dialog = new EmployeeRates(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        EmployeeRates dialog = new EmployeeRates(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        In dialog = new In(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed
    public static String date;

    final void setDate() {
        java.text.DateFormat dateFormat = new java.text.SimpleDateFormat("dd");
        jLabel118.setText("" + dateFormat.format(java.util.Calendar.getInstance().getTime()));
        dateFormat = new java.text.SimpleDateFormat("yyyy");
        jLabel117.setText("" + dateFormat.format(java.util.Calendar.getInstance().getTime()));
        dateFormat = new java.text.SimpleDateFormat("MMMM");
        jLabel116.setText("" + dateFormat.format(java.util.Calendar.getInstance().getTime()));
        dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
        date = "" + dateFormat.format(java.util.Calendar.getInstance().getTime());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qwerty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Qwerty().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}